---
title: フロー実行をキャンセル
description: フロー実行をキャンセルするさまざまな方法を学習します。
---

CLI、UI、REST API、または Python クライアントから、スケジュールされたフロー実行または進行中のフロー実行をキャンセルできます。

{/*
<!-- vale off -->
*/}

キャンセルを要求すると、フロー実行は「キャンセル中」状態に移行します。
ワーカーを使用したワークプールベースのデプロイメントの場合、ワーカーはフロー実行の状態を監視し、キャンセルが要求されたことを検出します。
ワーカーはフロー実行インフラストラクチャにシグナルを送信し、実行の終了を要求します。
猶予期間（デフォルトは30秒）が経過しても実行が終了しない場合、インフラストラクチャは強制終了され、フロー実行が確実に終了します。


{/*
<!-- vale on -->
*/}

<Warning>
**デプロイメントが必要です**

フロー実行をキャンセルするには、フロー実行がデプロイメントに関連付けられている必要があります。
キャンセルを強制するには、監視プロセスが実行されている必要があります。

インラインでネストされたフロー実行（`run_deployment` を使用せずに作成されたもの）は、親フロー実行をキャンセルしなければキャンセルできません。
親フロー実行とは独立してネストされたフロー実行をキャンセルするには、個別にデプロイし、[run_deployment](/v3/deploy/index) 関数を使用して開始することをお勧めします。
</Warning>

キャンセルはPrefectワーカーの再起動の影響を受けません。
これを実現するために、作成されたインフラストラクチャに関するメタデータをフロー実行に添付します。
内部的には、これは「infrastructure_pid」またはインフラストラクチャ識別子と呼ばれます。
通常、これは2つの部分で構成されます。

- スコープ: インフラストラクチャの実行場所を識別します。
- ID: スコープ内でのインフラストラクチャの一意の識別子です。

{/*
<!-- vale off -->
*/}

スコープは、Prefect が間違ったインフラストラクチャを強制終了しないようにします。
たとえば、複数のマシンで実行されているワーカーはプロセス ID が重複している可能性がありますが、スコープは一致してはなりません。

{/*
<!-- vale on -->
*/}

インフラストラクチャタイプの識別子は次のとおりです。

- プロセス: マシンのホスト名とPID。
- Dockerコンテナ: Docker API URLとコンテナID。
- Kubernetesジョブ: Kubernetesクラスタ名とジョブ名。

キャンセルプロセスは堅牢ですが、いくつかの問題が発生する可能性があります。

- フロー実行のインフラストラクチャがキャンセルをサポートしていない場合、キャンセルは機能しません。
- フロー実行をキャンセルしようとしたときに識別子のスコープが一致しない場合、ワーカーはフロー実行をキャンセルできません。
別のワーカーがキャンセルを試行する場合があります。
- 実行に関連付けられたインフラストラクチャが見つからない、または既に強制終了されている場合、ワーカーはフロー実行をキャンセル済みとしてマークします。
- `infrastructre_pid` がない場合、フロー実行はキャンセル済みとしてマークされますが、キャンセルを強制することはできません。
- キャンセル中にワーカーが予期しないエラーに遭遇した場合、エラーの発生場所に応じて、フロー実行がキャンセルされるかどうかが決まります。
ワーカーはフロー実行のキャンセルを再試行します。別のワーカーがキャンセルを試行する場合があります。

### CLI 経由でキャンセルする

実行環境のコマンドラインから、フロー実行の ID を渡す「prefect flow-run cancel」CLI コマンドを使用して、フロー実行をキャンセルできます。

```bash
prefect flow-run cancel 'a55a4804-9e3c-4042-8b59-b3b6b7618736'
```

### UI からキャンセルする

フロー実行の詳細ページに移動し、右上の「キャンセル」をクリックします。

![Prefect UI](/v3/img/ui/flow-run-cancellation-ui.png)

## タイムアウト

フロータイムアウトは、意図しない長時間実行フローの発生を防ぎます。フローの実行時間がタイムアウトで指定された時間を超えると、タイムアウト例外が発生し、フローは失敗としてマークされます。
UIでは、フローは「TimedOut」と表示されます。

タイムアウト時間は、キーワード引数「timeout_seconds」を使用して指定します。

```python
from prefect import flow
import time

@flow(timeout_seconds=1, log_prints=True)
def show_timeouts():
    print("I will execute")
    time.sleep(5)
    print("I will not execute")
```